### ISSUE TITLE
Tutorial "binning fake data" fails to execute

### ISSUE THREAD

**Issue by daviddoji** [OpenCOMPES/sed-binning#76]
First cell of tutorial 1 gives this nice error:
![image](https://user-images.githubusercontent.com/4411314/185410036-37a7b608-83c6-463b-a228-fdb0dad77c68.png)

In this case, it's easy to spot where the error is and it's quite easy to fix.

My point is that this type of errors MUST NOT be in the main branch, as they can easily be catched by the `pre-commit-hooks` and by the github action.
If we refuse to use the former and ignore the errors given by the latter, things like this happens. 

Please fix it.

**Comment by rettigl** [comment]
Suggestion: why don't you fix it?

**Comment by rettigl** [comment]
I generally agree, but instead of commenting fixing it is more productive. And I think the pre-commit hook would not have caught this, because the module has been renamend, and the tutorial file has not been commited, no? So also no pre-commit hooks run on it.

**Comment by rettigl** [comment]
It would e.g. be helpful if you write test functions for the example notebooks...

**Comment by steinnymir** [comment]
@daviddoji this was fixed in #77, right?

**Comment by daviddoji** [comment]
Yep. You can close it.
